project:
  type: website
  resources:
   - pubs
   - CNAME
   - images

website:
  title: "MIND Lab"
  site-url: https://mindlabpsych.org
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: People
        href: people.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Contact
        href: contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-after-body:
      - js/pubs-by-year.html

bibliography: publications.bib
csl: csl/apa.csl
